sping:
  profiles: 
   active: 
   - dev
service:
  port: 8088
---
spring:
  profiles: dev
  application:
    name: dev-springcloud
---
spring:
  profiles: test
  application:
    name: test-springcloud
